// generated by "sampctl package generate"
#include <a_samp>
#define YSI_YES_HEAP_MALLOC
#include "x_enex.inc"

main() {
	// write tests for libraries here and run "sampctl package run"	
	Enex_Create(207.6328, -61.6965, 1.9766, 179.7099, 286.1490, -40.6444, 1001.5156, 358.6616, 1, 1);
}

forward OnPlayerEnterEnEx(playerid, enexid);
public OnPlayerEnterEnEx(playerid, enexid)
{
	new name[MAX_PLAYER_NAME];
	GetPlayerName(playerid, name, sizeof name);
	if(strcmp(name, "XomoX", true) == 1) { // Name is not XomoX
		SendClientMessage(playerid, -1, "You're not XomoX");
		return 0;
	}
	SendClientMessage(playerid, -1, "Welcome XomoX");
	return 1;
}


forward OnPlayerEnteredEnEx(playerid, enexid);
public OnPlayerEnteredEnEx(playerid, enexid)
{
	SendClientMessage(playerid, -1, "You've entered an enex!");
	return 1;
}